# Generated by Django 4.1.2 on 2023-06-11 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("working_place", models.TextField()),
                ("text", models.TextField()),
                ("media", models.FileField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
        ),
    ]
